# Generated by Django 3.2 on 2022-03-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=200, verbose_name='Text')),
                ('link', models.CharField(default=None, max_length=200, verbose_name='Link Video')),
                ('is_active', models.BooleanField(default=False, verbose_name='In page?')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'ordering': ['-is_active'],
            },
        ),
    ]
